remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Why? 
description: Hello, I'm Dylan McEntyre, a young dude from Virginia and my favorite question is why. 
description: Hopefully this site will allow you to learn a bit about me and maybe even about themselves

text: Don't let this fool you, I have absolutely no clue what I'm doing.
