title: Dylan-McEntyre.io
email: d01j01m@gmail.com
description: This is my first real attempt at creating a website. Trying to learn by doing
url: "https://dylanjm987.github.io/Dylan-McEntyre.io/"

github_username:  dylanjm987

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
