remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Dylan McEntyre
description: Hopefully this site will be used as a portfolio

paragraph: Don't let this fool you. I have absolutely no clue what I'm doing, but I think the most important part is that I'm trying to make something. 
