title: Dylan McEntyre
email: d01j01m@gmail.com
description: "All I can control is me. Time and time again, after moments of struggle I had no choice but to surrender to the tides of life and their natural rhythms." -Tariq Trotter
url: https://dylanjm987.github.io/Dylan-McEntyre.io/

github_username:  dylanjm987
 
# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
