title: Dylan McEntyre
email: d01j01m@gmail.com
description: Be kind, for everyone you meet is fighting a harder battle. -Plato
url: https://dylanjm987.github.io/Dylan-McEntyre.io/

github_username:  dylanjm987

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
