remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Why? 

description: Hello, my name is Dylan. I am a guy from Virginia trying to figure things out one day at a time.  

text: A wise man once told me that life is learning so my goal with this website is to learn. To learn about web design, myself, and the world.

text: But, do not let this fool you, I have absolutely no clue what I'm doing.
